output_root: '../'
pytorch_data_dir: '$CUTS_ROOT/comparison/STEGO/data/'
experiment_name: "brats_seed2"
res: 128
num_workers: 1
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
- '$CUTS_ROOT/comparison/STEGO/checkpoints/brats_seed2/directory_brats_seed2/'

hydra:
  run:
    dir: "."
  output_subdir: ~
